import {
  Task,
  User,
  TimeLog,
  AdminConfig,
  ClassPeriod,
  ExamCountdown,
  Announcement,
  CategoryDef,
  AISummary,
  DailyTaskDefinition,
  DailyTaskCompletion,
  DailyHistoryRecord,
} from './types';

export const CURRENT_USER: User = {
  id: 'usr_1',
  name: 'Alex Rivera',
  email: 'alex.rivera@university.edu',
  role: 'user',
  theme_pref: 'glass',
  streak_count: 0,
  longest_streak: 0,
  xp: 0,
  level: 1,
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  department: 'Computer Science & Engineering',
};

export const ADMIN_USER: User = {
  id: 'usr_admin',
  name: 'Institutional Admin',
  email: '218r1a0543@gmail.com',
  role: 'admin',
  theme_pref: 'dark',
  streak_count: 0,
  longest_streak: 0,
  xp: 0,
  level: 1,
  avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  department: 'Academic Operations & Governance',
};

export const INITIAL_CATEGORIES: CategoryDef[] = [
  { id: 'cat_1', name: 'Morning Routine & Fitness', color: '#10b981', is_locked_by_admin: false, is_core_academic: false, icon: 'Sun' },
  { id: 'cat_2', name: "Spiritual & Qur'an", color: '#06b6d4', is_locked_by_admin: false, is_core_academic: false, icon: 'BookOpen' },
  { id: 'cat_3', name: 'Core Academic Classes', color: '#6366f1', is_locked_by_admin: true, is_core_academic: true, icon: 'GraduationCap' },
  { id: 'cat_4', name: 'UI & UX Design', color: '#ec4899', is_locked_by_admin: true, is_core_academic: true, icon: 'Layout' },
  { id: 'cat_5', name: 'Machine Learning (ML)', color: '#8b5cf6', is_locked_by_admin: true, is_core_academic: true, icon: 'Cpu' },
  { id: 'cat_6', name: 'Data Science (DS)', color: '#3b82f6', is_locked_by_admin: false, is_core_academic: true, icon: 'BarChart2' },
  { id: 'cat_7', name: 'Python Programming', color: '#f59e0b', is_locked_by_admin: false, is_core_academic: true, icon: 'Code' },
  { id: 'cat_8', name: 'SQL & Databases', color: '#14b8a6', is_locked_by_admin: false, is_core_academic: true, icon: 'Database' },
  { id: 'cat_9', name: 'DSA & Problem Solving', color: '#f43f5e', is_locked_by_admin: true, is_core_academic: true, icon: 'Layers' },
  { id: 'cat_10', name: 'Communication Skills', color: '#a855f7', is_locked_by_admin: false, is_core_academic: false, icon: 'MessageSquare' },
];

export const INITIAL_ADMIN_CONFIG: AdminConfig = {
  organization_name: 'Academic & Technical Curriculum',
  department: 'Computer Science, AI & Engineering',
  max_daily_hours_threshold: {
    value: 16,
    locked_by_admin: true,
  },
  gamification_enabled: {
    value: true,
    locked_by_admin: true,
  },
  rotation_cycle_current: 'A',
  ai_tone_persona: 'Encouraging Academic Mentor',
  timesheet_export_format: 'csv',
  auto_advance_rotation: true,
};

export const INITIAL_CLASS_PERIODS: ClassPeriod[] = [
  {
    id: 'per_1',
    name: 'Morning Block: Wake-Up & Qur’an',
    start_time: '05:00',
    end_time: '05:45',
    day_type: 'all',
    default_category: "Spiritual & Qur'an",
    room: 'Home Study',
  },
  {
    id: 'per_2',
    name: 'Morning Fitness: Walking',
    start_time: '05:45',
    end_time: '07:15',
    day_type: 'all',
    default_category: 'Morning Routine & Fitness',
    room: 'Outdoor Track',
  },
  {
    id: 'per_3',
    name: 'Morning Core: Communication, DSA & SQL',
    start_time: '08:00',
    end_time: '10:00',
    day_type: 'all',
    default_category: 'DSA & Problem Solving',
    room: 'Lab / Desk',
  },
  {
    id: 'per_4',
    name: 'Main Block: Regular Class',
    start_time: '10:30',
    end_time: '13:31',
    day_type: 'all',
    default_category: 'Core Academic Classes',
    room: 'Campus Lecture Hall',
  },
  {
    id: 'per_5',
    name: 'Evening Class: UI class',
    start_time: '18:30',
    end_time: '19:30',
    day_type: 'A',
    default_category: 'UI & UX Design',
    room: 'Design Studio / Online',
  },
  {
    id: 'per_6',
    name: 'Evening Deep Work: ML (Machine Learning)',
    start_time: '19:30',
    end_time: '21:00',
    day_type: 'all',
    default_category: 'Machine Learning (ML)',
    room: 'AI Workstation',
  },
  {
    id: 'per_7',
    name: 'Night Coding: DS Video & Python Practice',
    start_time: '21:00',
    end_time: '23:45',
    day_type: 'all',
    default_category: 'Python Programming',
    room: 'Personal Workspace',
  },
];

export const INITIAL_EXAMS: ExamCountdown[] = [
  {
    id: 'ex_1',
    subject: 'Machine Learning (ML)',
    title: 'ML Milestone Assessment: Supervised & Neural Models',
    date: '2026-09-18',
    time: '10:00 AM',
    weight_percent: 30,
    room: 'Tech Lab 101',
    topics: ['Regression & Classification', 'Gradient Descent', 'Loss Optimization', 'Evaluation Metrics'],
  },
  {
    id: 'ex_2',
    subject: 'DSA & Problem Solving',
    title: 'DSA Live Coding Contest: Trees & Dynamic Programming',
    date: '2026-09-28',
    time: '02:00 PM',
    weight_percent: 25,
    room: 'Turing Hall',
    topics: ['Binary Search Trees', 'Graph Traversals', 'DP Memoization', 'Time Complexity'],
  },
  {
    id: 'ex_3',
    subject: 'Python Programming',
    title: 'Python & SQL Backend Project Submission',
    date: '2026-10-15',
    time: '11:59 PM',
    weight_percent: 35,
    room: 'Online Portal',
    topics: ['Data Pipelines', 'SQL Joins & Indexing', 'API Integration', 'Data Science Libraries'],
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann_1',
    title: 'Schedule Updated: New Timetable Loaded Successfully',
    message: 'Your personal timetable has been synchronized with the updated schedule blocks (Wake-Up, Qur’an, Walking, Regular Class, UI class, ML, DS Video, Python Practice, SQL, Communication, and DSA).',
    date: '2026-08-31',
    severity: 'info',
    is_mandatory: true,
  },
  {
    id: 'ann_2',
    title: 'Python Practice & ML Daily Targets',
    message: 'Recommended: Complete your 1.5h Machine Learning module followed by the 2.5h Python Practice sprint each evening.',
    date: '2026-08-30',
    severity: 'info',
  },
];

const today = new Date().toISOString().split('T')[0];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'tsk_wakeup',
    user_id: 'usr_1',
    title: 'Wake-Up',
    category: 'Morning Routine & Fitness',
    date: today,
    start_time: '05:00',
    end_time: '05:30',
    duration_minutes: 30,
    priority: 'high',
    status: 'done',
    recurrence_rule: 'daily',
    is_admin_locked: false,
    time_spent_seconds: 1800,
    tags: ['Morning', 'Routine', '5:00-5:30'],
    notes: 'Wake up early, fresh start and morning hydration (5:00 - 5:30)',
  },
  {
    id: 'tsk_quran',
    user_id: 'usr_1',
    title: "Qur'an Reading",
    category: "Spiritual & Qur'an",
    date: today,
    start_time: '05:30',
    end_time: '05:45',
    duration_minutes: 15,
    priority: 'high',
    status: 'done',
    recurrence_rule: 'daily',
    is_admin_locked: false,
    time_spent_seconds: 900,
    tags: ['Spiritual', 'Daily Habit', '15mins'],
    notes: "Daily 15-minute Qur'an recitation and reflection (15 mins)",
  },
  {
    id: 'tsk_walking',
    user_id: 'usr_1',
    title: 'Walking',
    category: 'Morning Routine & Fitness',
    date: today,
    start_time: '05:45',
    end_time: '07:15',
    duration_minutes: 90,
    priority: 'medium',
    status: 'done',
    recurrence_rule: 'daily',
    is_admin_locked: false,
    time_spent_seconds: 5400,
    tags: ['Exercise', 'Health', '1-1/2 hr'],
    notes: 'Outdoor morning walking & physical exercise (1-1/2 hr / 90 mins)',
  },
  {
    id: 'tsk_comm',
    user_id: 'usr_1',
    title: 'Communication',
    category: 'Communication Skills',
    date: today,
    start_time: '08:00',
    end_time: '08:30',
    duration_minutes: 30,
    priority: 'medium',
    status: 'pending',
    recurrence_rule: 'daily',
    is_admin_locked: false,
    time_spent_seconds: 0,
    tags: ['Soft Skills', 'Speaking', '30min'],
    notes: 'Daily communication skill practice & articulation (30min)',
  },
  {
    id: 'tsk_dsa',
    user_id: 'usr_1',
    title: 'DSA',
    category: 'DSA & Problem Solving',
    date: today,
    start_time: '08:45',
    end_time: '09:15',
    duration_minutes: 30,
    priority: 'high',
    status: 'pending',
    recurrence_rule: 'daily',
    is_admin_locked: false,
    time_spent_seconds: 0,
    tags: ['Algorithms', 'LeetCode', '30mins'],
    notes: 'Data Structures & Algorithms practice (30mins)',
  },
  {
    id: 'tsk_sql',
    user_id: 'usr_1',
    title: 'SQL',
    category: 'SQL & Databases',
    date: today,
    start_time: '09:30',
    end_time: '10:00',
    duration_minutes: 30,
    priority: 'medium',
    status: 'pending',
    recurrence_rule: 'daily',
    is_admin_locked: false,
    time_spent_seconds: 0,
    tags: ['Database', 'Queries', '30mins'],
    notes: 'SQL practice, joins, group by, subqueries & schema design (30mins)',
  },
  {
    id: 'tsk_regular_class',
    user_id: 'usr_1',
    title: 'Rgular-class',
    category: 'Core Academic Classes',
    date: today,
    start_time: '10:30',
    end_time: '13:31',
    duration_minutes: 181,
    priority: 'high',
    status: 'pending',
    recurrence_rule: 'daily',
    is_admin_locked: true,
    time_spent_seconds: 0,
    tags: ['Academic', 'College', '10:30-1:31'],
    room: 'Main Lecture Hall',
    notes: 'Regular college / university class block (10:30 - 1:31)',
  },
  {
    id: 'tsk_ui_class',
    user_id: 'usr_1',
    title: 'UI class',
    category: 'UI & UX Design',
    date: today,
    start_time: '18:30',
    end_time: '19:30',
    duration_minutes: 60,
    priority: 'high',
    status: 'pending',
    recurrence_rule: 'daily',
    is_admin_locked: true,
    time_spent_seconds: 0,
    tags: ['Design', 'Figma', '6:30-7:30'],
    room: 'Design Studio',
    notes: 'UI class & design principles (6:30 - 7:30)',
  },
  {
    id: 'tsk_ml',
    user_id: 'usr_1',
    title: 'ML',
    category: 'Machine Learning (ML)',
    date: today,
    start_time: '19:30',
    end_time: '21:00',
    duration_minutes: 90,
    priority: 'high',
    status: 'pending',
    recurrence_rule: 'daily',
    is_admin_locked: false,
    time_spent_seconds: 0,
    tags: ['AI', 'Machine Learning', '1hr/30mins'],
    notes: 'Machine Learning models, algorithms & math practice (1hr/30mins)',
  },
  {
    id: 'tsk_ds_video',
    user_id: 'usr_1',
    title: 'DS Video',
    category: 'Data Science (DS)',
    date: today,
    start_time: '21:00',
    end_time: '21:30',
    duration_minutes: 30,
    priority: 'medium',
    status: 'pending',
    recurrence_rule: 'daily',
    is_admin_locked: false,
    time_spent_seconds: 0,
    tags: ['Video', 'Data Science', '15-30mins'],
    notes: 'Data Science educational video & tutorial walkthrough (15-30mins)',
  },
  {
    id: 'tsk_python_practice',
    user_id: 'usr_1',
    title: 'PytonPractice',
    category: 'Python Programming',
    date: today,
    start_time: '21:30',
    end_time: '23:45',
    duration_minutes: 135,
    priority: 'high',
    status: 'pending',
    recurrence_rule: 'daily',
    is_admin_locked: false,
    time_spent_seconds: 0,
    tags: ['Coding', 'Python', '2-3hr'],
    notes: 'Hands-on Python coding practice, building scripts & problem sets (2-3hr)',
  },
];

export const INITIAL_TIME_LOGS: TimeLog[] = [
  {
    id: 'log_1',
    task_id: 'tsk_wakeup',
    user_id: 'usr_1',
    task_title: 'Wake-Up',
    category: 'Morning Routine & Fitness',
    started_at: '2026-08-31T05:00:00Z',
    ended_at: '2026-08-31T05:30:00Z',
    duration_seconds: 1800,
    notes: 'Early wake-up completed on time',
  },
  {
    id: 'log_2',
    task_id: 'tsk_quran',
    user_id: 'usr_1',
    task_title: "Qur'an Reading",
    category: "Spiritual & Qur'an",
    started_at: '2026-08-31T05:30:00Z',
    ended_at: '2026-08-31T05:45:00Z',
    duration_seconds: 900,
    notes: 'Daily recitation session completed',
  },
  {
    id: 'log_3',
    task_id: 'tsk_walking',
    user_id: 'usr_1',
    task_title: 'Walking',
    category: 'Morning Routine & Fitness',
    started_at: '2026-08-31T05:45:00Z',
    ended_at: '2026-08-31T07:15:00Z',
    duration_seconds: 5400,
    notes: '1.5 hours brisk morning walk and cardio',
  },
];

export const INITIAL_AI_SUMMARY: AISummary = {
  id: 'sum_1',
  user_id: 'usr_1',
  week_of: 'Aug 25 - Aug 31, 2026',
  insight_text: 'Your updated schedule effectively balances physical & spiritual well-being (Wake-Up, Qur’an, Walking) with technical mastery across Regular Classes, UI class, ML, Data Science, Python Practice, SQL, Communication, and DSA. Morning habits (5:00 - 7:15 AM) provide solid momentum for deep evening coding blocks.',
  generated_at: '2026-08-31T07:00:00Z',
  metrics: {
    total_completed: 3,
    completion_rate: 27.3,
    peak_productivity_window: '05:00 AM - 07:15 AM & 19:30 PM - 23:45 PM',
    skip_analysis: 'Zero missed routines today.',
    recommended_focus_adjustment: 'Begin your evening ML & Python Practice promptly after UI class.',
  },
};

// Permanent 10 Recurring Daily Tasks (Source of Truth from provided spreadsheet image)
export const PERMANENT_DAILY_TASKS: DailyTaskDefinition[] = [
  {
    id: 'dt_1',
    order: 1,
    title: 'Wake-Up',
    time_slot: '5:00 - 5:30',
    duration_minutes: 30,
    category: 'Morning Routine & Fitness',
    notes: 'Early morning wake-up and hydration (5:00 - 5:30)',
    icon: 'Sun',
  },
  {
    id: 'dt_2',
    order: 2,
    title: "Qur'an Reading",
    time_slot: '15mins',
    duration_minutes: 15,
    category: "Spiritual & Qur'an",
    notes: "Daily Qur'an recitation and spiritual focus (15 mins)",
    icon: 'BookOpen',
  },
  {
    id: 'dt_3',
    order: 3,
    title: 'Walking',
    time_slot: '1-1/2 hr',
    duration_minutes: 90,
    category: 'Morning Routine & Fitness',
    notes: 'Morning walking exercise and fresh air (1-1/2 hr)',
    icon: 'Activity',
  },
  {
    id: 'dt_4',
    order: 4,
    title: 'Rgular-class',
    time_slot: '10:30 - 1:31',
    duration_minutes: 181,
    category: 'Core Academic Classes',
    notes: 'University & department regular lecture blocks (10:30 - 1:31)',
    icon: 'GraduationCap',
  },
  {
    id: 'dt_5',
    order: 5,
    title: 'ML',
    time_slot: '1hr/30mins',
    duration_minutes: 90,
    category: 'Machine Learning (ML)',
    notes: 'Machine Learning model architecture & concepts (1hr/30mins)',
    icon: 'Cpu',
  },
  {
    id: 'dt_6',
    order: 6,
    title: 'Data Science Video',
    time_slot: '15-30mins',
    duration_minutes: 30,
    category: 'Data Science (DS)',
    notes: 'Data Science technical lecture or conceptual video (15-30mins)',
    icon: 'Video',
  },
  {
    id: 'dt_7',
    order: 7,
    title: 'PytonPractice',
    time_slot: '2-3hr',
    duration_minutes: 150,
    category: 'Python Programming',
    notes: 'Hands-on Python coding exercises & scripts (2-3hr)',
    icon: 'Code',
  },
  {
    id: 'dt_8',
    order: 8,
    title: 'SQL',
    time_slot: '30mins',
    duration_minutes: 30,
    category: 'SQL & Databases',
    notes: 'Relational queries, schema design & practice (30mins)',
    icon: 'Database',
  },
  {
    id: 'dt_9',
    order: 9,
    title: 'Communication',
    time_slot: '30min',
    duration_minutes: 30,
    category: 'Communication Skills',
    notes: 'Verbal, professional & presentation skills development (30min)',
    icon: 'MessageSquare',
  },
  {
    id: 'dt_10',
    order: 10,
    title: 'DSA',
    time_slot: '30mins',
    duration_minutes: 30,
    category: 'DSA & Problem Solving',
    notes: 'Data Structures and Algorithms LeetCode / problem solving (30mins)',
    icon: 'Layers',
  },
];

// Initial Historical Daily Task Completions corresponding to user participation records (from 30-08-2026 only)
export const INITIAL_DAILY_COMPLETIONS: DailyTaskCompletion[] = [
  // 30-08-2026 (Day before yesterday: 6/10 tasks completed)
  { id: 'dtc_3008_1', user_id: 'usr_1', task_id: 'dt_1', date: '2026-08-30', completed: true, completed_at: '2026-08-30T05:30:00Z' },
  { id: 'dtc_3008_2', user_id: 'usr_1', task_id: 'dt_2', date: '2026-08-30', completed: true, completed_at: '2026-08-30T05:45:00Z' },
  { id: 'dtc_3008_3', user_id: 'usr_1', task_id: 'dt_3', date: '2026-08-30', completed: true, completed_at: '2026-08-30T07:15:00Z' },
  { id: 'dtc_3008_4', user_id: 'usr_1', task_id: 'dt_4', date: '2026-08-30', completed: true, completed_at: '2026-08-30T13:30:00Z' },
  { id: 'dtc_3008_6', user_id: 'usr_1', task_id: 'dt_6', date: '2026-08-30', completed: true, completed_at: '2026-08-30T19:00:00Z' },
  { id: 'dtc_3008_7', user_id: 'usr_1', task_id: 'dt_7', date: '2026-08-30', completed: true, completed_at: '2026-08-30T22:30:00Z' },

  // 31-08-2026 (Row 1 / Yesterday: 5/10 completed)
  { id: 'dtc_3108_1', user_id: 'usr_1', task_id: 'dt_1', date: '2026-08-31', completed: true, completed_at: '2026-08-31T05:25:00Z' },
  { id: 'dtc_3108_2', user_id: 'usr_1', task_id: 'dt_2', date: '2026-08-31', completed: true, completed_at: '2026-08-31T05:42:00Z' },
  { id: 'dtc_3108_3', user_id: 'usr_1', task_id: 'dt_3', date: '2026-08-31', completed: true, completed_at: '2026-08-31T07:10:00Z' },
  { id: 'dtc_3108_4', user_id: 'usr_1', task_id: 'dt_4', date: '2026-08-31', completed: true, completed_at: '2026-08-31T13:30:00Z' },
  { id: 'dtc_3108_7', user_id: 'usr_1', task_id: 'dt_7', date: '2026-08-31', completed: true, completed_at: '2026-08-31T22:30:00Z' },

  // 01-09-2026 (Row 2 / Today: Qur'an done)
  { id: 'dtc_0109_2', user_id: 'usr_1', task_id: 'dt_2', date: '2026-09-01', completed: true, completed_at: '2026-09-01T05:40:00Z' },
];

