import {
  Task,
  User,
  TimeLog,
  AdminConfig,
  ClassPeriod,
  ExamCountdown,
  Announcement,
  CategoryDef,
  AISummary,
} from './types';

export const CURRENT_USER: User = {
  id: 'usr_1',
  name: 'Alex Rivera',
  email: 'alex.rivera@university.edu',
  role: 'user',
  theme_pref: 'glass',
  streak_count: 7,
  longest_streak: 14,
  xp: 1450,
  level: 4,
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  department: 'Computer Science & Engineering',
};

export const ADMIN_USER: User = {
  id: 'usr_admin',
  name: 'Dr. Eleanor Vance',
  email: 'e.vance@university.edu',
  role: 'admin',
  theme_pref: 'dark',
  streak_count: 22,
  longest_streak: 45,
  xp: 4800,
  level: 9,
  avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  department: 'Academic Operations & Governance',
};

export const INITIAL_CATEGORIES: CategoryDef[] = [
  { id: 'cat_1', name: 'Database Systems (DBMS)', color: '#6366f1', is_locked_by_admin: true, is_core_academic: true, icon: 'Database' },
  { id: 'cat_2', name: 'Algorithms & Data Structs', color: '#06b6d4', is_locked_by_admin: true, is_core_academic: true, icon: 'Code' },
  { id: 'cat_3', name: 'Physics & Electro-dynamics', color: '#ec4899', is_locked_by_admin: true, is_core_academic: true, icon: 'Atom' },
  { id: 'cat_4', name: 'Team Project / Lab', color: '#10b981', is_locked_by_admin: false, is_core_academic: true, icon: 'Users' },
  { id: 'cat_5', name: 'Exam Prep & Self Study', color: '#f59e0b', is_locked_by_admin: false, is_core_academic: false, icon: 'BookOpen' },
  { id: 'cat_6', name: 'Work / Part-time Shift', color: '#8b5cf6', is_locked_by_admin: false, is_core_academic: false, icon: 'Briefcase' },
];

export const INITIAL_ADMIN_CONFIG: AdminConfig = {
  organization_name: 'MIT / Stanford Academic Consortium',
  department: 'School of Engineering & Applied Sciences',
  max_daily_hours_threshold: {
    value: 16,
    locked_by_admin: true,
  },
  gamification_enabled: {
    value: true,
    locked_by_admin: true,
  },
  rotation_cycle_current: 'A',
  ai_tone_persona: 'Encouraging Academic Mentor',
  timesheet_export_format: 'csv',
  auto_advance_rotation: true,
};

export const INITIAL_CLASS_PERIODS: ClassPeriod[] = [
  {
    id: 'per_1',
    name: 'Period 1: Advanced Database Architecture',
    start_time: '08:30',
    end_time: '10:00',
    day_type: 'A',
    default_category: 'Database Systems (DBMS)',
    room: 'Hall B-201',
  },
  {
    id: 'per_2',
    name: 'Period 2: Algorithms & Graph Optimization',
    start_time: '10:15',
    end_time: '11:45',
    day_type: 'all',
    default_category: 'Algorithms & Data Structs',
    room: 'Turing Auditorium 101',
  },
  {
    id: 'per_3',
    name: 'Period 3: Quantum & Solid State Physics',
    start_time: '12:30',
    end_time: '14:00',
    day_type: 'B',
    default_category: 'Physics & Electro-dynamics',
    room: 'Science Complex 4A',
  },
  {
    id: 'per_4',
    name: 'Period 4: Distributed Systems & DB Lab',
    start_time: '14:30',
    end_time: '16:00',
    day_type: 'A',
    default_category: 'Team Project / Lab',
    room: 'Innovation Lab 2',
  },
  {
    id: 'per_5',
    name: 'Period 5: Campus IT Engineering Shift',
    start_time: '17:30',
    end_time: '19:30',
    day_type: 'all',
    default_category: 'Work / Part-time Shift',
    room: 'Tech Central Hub',
  },
];

export const INITIAL_EXAMS: ExamCountdown[] = [
  {
    id: 'ex_1',
    subject: 'Database Systems (DBMS)',
    title: 'Midterm Exam 1: ACID & B+ Tree Indices',
    date: '2026-09-18',
    time: '09:00 AM',
    weight_percent: 30,
    room: 'Hall B-201',
    topics: ['B+ Trees', 'Concurrency Isolation', 'WAL Logging', 'Query Plans'],
  },
  {
    id: 'ex_2',
    subject: 'Algorithms & Data Structs',
    title: 'Milestone 2: Dynamic Programming & Graphs',
    date: '2026-09-28',
    time: '10:15 AM',
    weight_percent: 25,
    room: 'Turing Auditorium 101',
    topics: ['Bellman-Ford', 'Max Flow Min Cut', 'DP Memoization', 'NP-Completeness'],
  },
  {
    id: 'ex_3',
    subject: 'Physics & Electro-dynamics',
    title: 'Semester Final Assessment: Maxwell Equations',
    date: '2026-10-15',
    time: '01:00 PM',
    weight_percent: 40,
    room: 'Science Complex 4A',
    topics: ['Electromagnetic Radiation', 'Waveguides', 'Relativistic Electrodynamics'],
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann_1',
    title: 'Institutional Schedule Override: Friday follows Cycle A Timetable',
    message: 'Due to the upcoming faculty symposium, this Friday will follow Cycle A-Day rotating periods regardless of normal weekly sequence.',
    date: '2026-08-31',
    severity: 'warning',
    is_mandatory: true,
  },
  {
    id: 'ann_2',
    title: 'Midterm Room Assignments Published',
    message: 'All midterm rooms for DBMS and Physics have been locked by the Dean of Studies. Please verify your exam widgets.',
    date: '2026-08-30',
    severity: 'info',
  },
];

const today = new Date().toISOString().split('T')[0];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'tsk_1',
    user_id: 'usr_1',
    title: 'DBMS Lecture: B+ Tree Indexing & Transaction Concurrency',
    category: 'Database Systems (DBMS)',
    date: today,
    start_time: '08:30',
    end_time: '10:00',
    duration_minutes: 90,
    priority: 'high',
    status: 'done',
    recurrence_rule: 'rotating_A',
    is_admin_locked: true,
    time_spent_seconds: 5400,
    tags: ['Core Class', 'Lecture'],
    room: 'Hall B-201',
    notes: 'Covered write-ahead logging (WAL) and B+ tree node splits.',
  },
  {
    id: 'tsk_2',
    user_id: 'usr_1',
    title: 'Algorithms Problem Set: Dynamic Programming Knapsack',
    category: 'Algorithms & Data Structs',
    date: today,
    start_time: '10:15',
    end_time: '11:45',
    duration_minutes: 90,
    priority: 'high',
    status: 'done',
    recurrence_rule: 'daily',
    is_admin_locked: false,
    time_spent_seconds: 5120,
    tags: ['Problem Set', 'Deep Work'],
    room: 'Turing Auditorium 101',
  },
  {
    id: 'tsk_3',
    user_id: 'usr_1',
    title: 'Midday Cognitive Recharge & Healthy Lunch',
    category: 'Exam Prep & Self Study',
    date: today,
    start_time: '12:00',
    end_time: '12:45',
    duration_minutes: 45,
    priority: 'low',
    status: 'done',
    recurrence_rule: 'daily',
    is_admin_locked: false,
    time_spent_seconds: 2700,
    tags: ['Health', 'Break'],
  },
  {
    id: 'tsk_4',
    user_id: 'usr_1',
    title: 'Capstone Team Standup & Sprint Planning',
    category: 'Team Project / Lab',
    date: today,
    start_time: '13:00',
    end_time: '13:45',
    duration_minutes: 45,
    priority: 'medium',
    status: 'done',
    recurrence_rule: 'weekly',
    is_admin_locked: false,
    time_spent_seconds: 2820,
    tags: ['Agile', 'Team'],
  },
  {
    id: 'tsk_5',
    user_id: 'usr_1',
    title: 'Implement Database Query Optimizer Mock (C++/Rust)',
    category: 'Team Project / Lab',
    date: today,
    start_time: '14:00',
    end_time: '15:30',
    duration_minutes: 90,
    priority: 'high',
    status: 'done',
    recurrence_rule: 'none',
    is_admin_locked: false,
    time_spent_seconds: 5460,
    tags: ['Coding', 'Capstone'],
    notes: 'Implemented cost model for hash joins vs nested loops.',
  },
  {
    id: 'tsk_6',
    user_id: 'usr_1',
    title: 'Physics Chapter 4: Maxwell Magnetic Flux Equations',
    category: 'Physics & Electro-dynamics',
    date: today,
    start_time: '15:45',
    end_time: '16:45',
    duration_minutes: 60,
    priority: 'medium',
    status: 'done',
    recurrence_rule: 'rotating_B',
    is_admin_locked: true,
    time_spent_seconds: 3600,
    tags: ['Theory', 'Core Class'],
    room: 'Science Complex 4A',
  },
  {
    id: 'tsk_7',
    user_id: 'usr_1',
    title: 'Review Midterm Flashcards & Practice Problems',
    category: 'Exam Prep & Self Study',
    date: today,
    start_time: '17:00',
    end_time: '17:45',
    duration_minutes: 45,
    priority: 'high',
    status: 'done',
    recurrence_rule: 'none',
    is_admin_locked: false,
    time_spent_seconds: 2700,
    tags: ['Anki', 'Revision'],
  },
  {
    id: 'tsk_8',
    user_id: 'usr_1',
    title: 'Part-time Tech Support Shift: Ticket Triage & Debugging',
    category: 'Work / Part-time Shift',
    date: today,
    start_time: '18:00',
    end_time: '19:30',
    duration_minutes: 90,
    priority: 'medium',
    status: 'done',
    recurrence_rule: 'daily',
    is_admin_locked: true,
    time_spent_seconds: 5350,
    tags: ['Work', 'Income'],
    room: 'Tech Central Hub',
  },
  {
    id: 'tsk_9',
    user_id: 'usr_1',
    title: 'Evening Deep Reading: Distributed Consensus Raft Paper',
    category: 'Database Systems (DBMS)',
    date: today,
    start_time: '20:00',
    end_time: '21:00',
    duration_minutes: 60,
    priority: 'medium',
    status: 'pending',
    recurrence_rule: 'none',
    is_admin_locked: false,
    time_spent_seconds: 0,
    tags: ['Reading', 'Research'],
    notes: 'Analyze leader election and log replication invariants.',
  },
  {
    id: 'tsk_10',
    user_id: 'usr_1',
    title: 'Daily Reflection & Tomorrow Timetable Planning',
    category: 'Exam Prep & Self Study',
    date: today,
    start_time: '21:15',
    end_time: '21:45',
    duration_minutes: 30,
    priority: 'low',
    status: 'pending',
    recurrence_rule: 'daily',
    is_admin_locked: false,
    time_spent_seconds: 0,
    tags: ['Planning', 'Habit'],
  },
];

export const INITIAL_TIME_LOGS: TimeLog[] = [
  {
    id: 'log_1',
    task_id: 'tsk_1',
    user_id: 'usr_1',
    task_title: 'DBMS Lecture: B+ Tree Indexing & Transaction Concurrency',
    category: 'Database Systems (DBMS)',
    started_at: '2026-08-31T08:30:00Z',
    ended_at: '2026-08-31T10:00:00Z',
    duration_seconds: 5400,
    notes: 'Class focus session',
  },
  {
    id: 'log_2',
    task_id: 'tsk_2',
    user_id: 'usr_1',
    task_title: 'Algorithms Problem Set: Dynamic Programming Knapsack',
    category: 'Algorithms & Data Structs',
    started_at: '2026-08-31T10:15:00Z',
    ended_at: '2026-08-31T11:40:00Z',
    duration_seconds: 5120,
    notes: 'High flow state',
  },
  {
    id: 'log_3',
    task_id: 'tsk_4',
    user_id: 'usr_1',
    task_title: 'Capstone Team Standup & Sprint Planning',
    category: 'Team Project / Lab',
    started_at: '2026-08-31T13:00:00Z',
    ended_at: '2026-08-31T13:47:00Z',
    duration_seconds: 2820,
  },
  {
    id: 'log_4',
    task_id: 'tsk_5',
    user_id: 'usr_1',
    task_title: 'Implement Database Query Optimizer Mock (C++/Rust)',
    category: 'Team Project / Lab',
    started_at: '2026-08-31T14:00:00Z',
    ended_at: '2026-08-31T15:28:00Z',
    duration_seconds: 5460,
  },
  {
    id: 'log_5',
    task_id: 'tsk_8',
    user_id: 'usr_1',
    task_title: 'Part-time Tech Support Shift: Ticket Triage & Debugging',
    category: 'Work / Part-time Shift',
    started_at: '2026-08-31T18:00:00Z',
    ended_at: '2026-08-31T19:28:00Z',
    duration_seconds: 5350,
  },
];

export const INITIAL_AI_SUMMARY: AISummary = {
  id: 'sum_1',
  user_id: 'usr_1',
  week_of: 'Aug 25 - Aug 31, 2026',
  insight_text: 'You maintained an outstanding 84% weekly completion rate (8 / 10 completed today)! Your deep work velocity peaks between 08:30 AM and 11:30 AM (completing technical tasks ~40% faster than evening slots). Evening study blocks past 8:30 PM experienced slight friction — shifting high-cognitive physics theory before dinner will save 45 minutes of friction.',
  generated_at: '2026-08-31T07:00:00Z',
  metrics: {
    total_completed: 42,
    completion_rate: 84.5,
    peak_productivity_window: '08:30 AM - 11:30 AM',
    skip_analysis: 'Evening physics theory had 2 skips due to fatigue after work shifts.',
    recommended_focus_adjustment: 'Schedule high-priority problem sets during Morning Period 1 & 2.',
  },
};
